version: '3'

vars:
  BINARY: main.wasm

tasks:
  build:
    desc: Build the WASM binary
    cmds:
      - tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o {{.BINARY}} .

  dev:
    desc: Run the app locally with live reload
    dotenv: ['.env.local']
    cmds:
      - spin build --up

  run:
    desc: Run the app locally (requires building first)
    dotenv: ['.env.local']
    cmds:
      - spin up

  clear:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY}}
      - rm -f .spin/
      - echo "Cleaned build artifacts"

  sync:
    desc: Sync Go dependencies and update go.sum
    cmds:
      - go mod tidy
      - go mod download
      - go mod verify

  deploy:
    desc: Deploy to Fermyon Cloud
    cmds:
      - spin cloud deploy

  test:
    desc: Run tests
    cmds:
      - go test ./...

  default:
    desc: Show available tasks
    cmds:
      - task --list
